language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run docs:build
deploy:
  provider: pages
  cleanup: false
  local_dir: docs/.vuepress/dist
  keep_history: true
  fqdn: www.zidon.net
  token: $GITHUB_TOKEN
  on:
    branch: master

