language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run docs:build # npm run docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  keep_history: true
  fqdn: zidon.net
  on:
    branch: master

