language: node_js
node_js:
  - lts/*
install:
  - yarn install
script:
  - yarn global add vuepress
  - yarn docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  keep_history: true
  fqdn: zidon.net
  github_token: $GITHUB_TOKEN
  on:
    branch: master

